### ISSUE TITLE
crash when overriding some of my C++ native event and blueprint implementable event

### ISSUE THREAD

**Issue by Sam-Online** [pixeltris/USharp#106] opened 2019-08-03 15:45 UTC
When I override some method in my C++ classes the CS part crash (well tbh it crash the entire 
 editor/project) saying this:
![image](https://user-images.githubusercontent.com/8966225/62413944-76645000-b5e3-11e9-9088-2ac89db06489.png)

then this:

![image](https://user-images.githubusercontent.com/8966225/62413947-84b26c00-b5e3-11e9-98ae-65e0c9187bbe.png)

is this a known issue, am i doing something wrong

here's the C# version of the method:
`protected override void Restart_Implementation( ) {
	base.Restart_Implementation( );
	AbilitySystem.RefreshAbilityActorInfo( );
}`

here's the CPP signature:
`UFUNCTION(BlueprintImplementableEvent)
	void K2_Restart( );`

**Comment by pixeltris** [comment] 2019-08-03 16:50
It's hard to determine the cause of the first error. It's crashing when constructing a function parameter, possibly an invalid function param type? You should be able to place a breakpoint down [here](https://github.com/pixeltris/USharp/blob/b5a012f789a9efbfcc49c6b125478d2431f21e31/Managed/UnrealEngine.Runtime/UnrealEngine.Runtime/Internal/ManagedUnrealTypes.Builder.cs#L1374) and check that `outer` / `propertyClass` aren't null and that `propertyName` isn't an empty string. If you're able to create a code snippet which reproduces the error, I can try debugging it if you're not sure what to do.

If that second error message appears after the first, then something is already corrupt so it's best to deal with the first error (which should also fix the second error).

**Comment by pixeltris** [comment] 2019-08-03 17:38
From my testing the 'K2_' isn't the issue. It could be that it isn't an issue at all with that function, but instead a different function. If you're able to create a reproducible snippet of code that would be great.

**Comment by Sam-Online** [comment] 2019-08-04 02:35
Ok, after more testing it turns out usharp doesn't like C++ interfaces. it crashes as soon as I add it to my C# class.

**Comment by pixeltris** [comment] 2019-08-04 17:23
I haven't been able to reproduce the issue with that exact setup. Does `AMyCharacter` implement any interfaces?

**Comment by Sam-Online** [comment] 2019-08-04 20:18
no it doesn't... i'll try to recompile the plugin from source to see if what happend... I'll send you the project, this will compile and run just fine, but this version of CSMyCharacter.cs won't
```cs
using UnrealEngine.Engine;
using UnrealEngine.Runtime;

namespace cs_crash {
	[UClass]
	//public class ACSMyCharacter: AActor {
	public class ACSMyCharacter: AActor, IMyCharacterInterface {
		public override void Initialize(FObjectInitializer Initializer) {
			base.Initialize(Initializer);
		}

		public void StopAnimSetMontage(UAnimSequence AnimSet) {
			throw new System.NotImplementedException( );
		}

		public UAnimMontage PlayAnimSetMontage(UAnimSequence AnimSet, float InPlayRate, FName StartSectionName) {
			throw new System.NotImplementedException( );
		}

		public UActorComponent GetWeaponComponent( ) {
			throw new System.NotImplementedException( );
		}

		public USceneComponent GetWeaponAttachmentComponent( ) {
			throw new System.NotImplementedException( );
		}

		public APlayerState GetLinkedPlayerState( ) {
			throw new System.NotImplementedException( );
		}

		public float GetEyeHeight( ) {
			throw new System.NotImplementedException( );
		}

		public UActorComponent GetBuildModeComponent( ) {
			throw new System.NotImplementedException( );
		}

		public FRotator GetAimRotation( ) {
			throw new System.NotImplementedException( );
		}



		public virtual void StopAnimSetMontage_Implementation(UAnimSequence AnimSet) {
		}

		public virtual UAnimMontage PlayAnimSetMontage_Implementation(UAnimSequence AnimSet, float InPlayRate, FName StartSectionName) {
			return null;
		}

		public virtual UActorComponent GetWeaponComponent_Implementation( ) {
			return null;
		}

		public virtual USceneComponent GetWeaponAttachmentComponent_Implementation( ) {
			return null;
		}

		public virtual APlayerState GetLinkedPlayerState_Implementation( ) {
			return null;
		}

		public virtual float GetEyeHeight_Implementation( ) {
			return 0f;
		}

		public virtual UActorComponent GetBuildModeComponent_Implementation( ) {
			return null;
		}

		public virtual FRotator GetAimRotation_Implementation( ) {
			return FRotator.ZeroRotator;
		}
	}
}
```
[cs_crash.zip](https://github.com/pixeltris/USharp/files/3465289/cs_crash.zip)

**Comment by pixeltris** [comment] 2019-08-04 23:11
Thanks, I can reproduce the issue on my machine. It looks like it's a bug with AssemblyRewriter on function names. I'll look into it some more and try to create a fix.

**Comment by pixeltris** [comment] 2019-08-04 23:30
Should be fixed in https://github.com/pixeltris/USharp/commit/d8abadf8c80a76790d2d2e9febae164e5735ab50. Let me know if it works for you.

**Comment by Sam-Online** [comment] 2019-08-05 00:44
preliminary tests seem good, I'll test in my real project tomorrow morning, thx! ^^

**Closed** 2019-08-09 10:54 UTC
